import { fal } from "@fal-ai/client";
import { GamePart } from '../types';

const configureFal = () => {
  const apiKey = process.env.FAL_KEY;
  if (!apiKey) throw new Error("FAL_KEY not found in environment");
  fal.config({ credentials: apiKey });
};

export const generateAssetArt = async (
  originalImageBase64: string,
  layoutTemplateBase64: string,
  parts: GamePart[],
  stylePrompt: string = "Detailed, clean 2D game art style, vibrant colors"
): Promise<string> => {
  configureFal();

  // Create number-to-part mapping (matches numbers drawn on atlas)
  const mapping = parts.map((p, index) => {
    const num = index + 1;
    const poly = p.mask.polygon;
    const target = p.atlasRect!;
    const polyStr = poly.map(pt => `(${pt.x},${pt.y})`).join(' ');
    return `- Box #${num} = "${p.name}": (Mask polygon: ${polyStr}) -> (Target rect in layout: [${target.x},${target.y},${target.w},${target.h}])`;
  }).join("\n");

  const fullPrompt = `
TASK: separate the original image into parts.

INPUTS:
1. ORIGINAL_IMAGE: The original object with all parts anotated.
2. LAYOUT_TEMPLATE: A square image with numbered boxes (1, 2, 3...) where you must draw the parts.

NUMBER-TO-PART MAPPING:
${mapping}

INSTRUCTIONS:
- Each numbered box in the LAYOUT_TEMPLATE corresponds to a part from the ORIGINAL_IMAGE.
- Fill each numbered box with the corresponding part from the ORIGINAL_IMAGE without changing the perspective or style.
- DO NOT include the dashed bounding box lines or numbers in your output.
- OUTPUT MUST ONLY BE THE DRAWN PARTS on a clean white background.
- OCCLUSION HANDLING: For parts partially hidden in the original image, generate the ENTIRE part as it would look if fully visible and detached.
- Keep lighting, style, and perspective consistent across all parts.
  `.trim();

  const originalImageDataUrl = `data:image/png;base64,${originalImageBase64}`;
  const layoutTemplateDataUrl = `data:image/png;base64,${layoutTemplateBase64}`;

  const result = await fal.subscribe("fal-ai/flux-2-pro/edit", {
    input: {
      prompt: fullPrompt,
      image_size: "auto",
      safety_tolerance: "2",
      enable_safety_checker: true,
      output_format: "png",
      image_urls: [originalImageDataUrl, layoutTemplateDataUrl]
    },
    logs: true,
    onQueueUpdate: (update) => {
      if (update.status === "IN_PROGRESS" && update.logs) {
        update.logs.map((log) => log.message).forEach(console.log);
      }
    },
  });

  const data = result.data as { images?: Array<{ url: string }> };
  
  if (data.images && data.images.length > 0) {
    const imageUrl = data.images[0].url;
    
    const response = await fetch(imageUrl);
    const blob = await response.blob();
    
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onloadend = () => {
        const base64 = (reader.result as string).split(',')[1];
        resolve(base64);
      };
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  }

  throw new Error("No image generated by fal.ai");
};
